"""
Seed simulated inventory for WSM Kendra ranking.

This script:
- Reads all medicines from MongoDB.
- Reads all active Kendras.
- Assigns every medicine to up to three Kendras.
- Adds different prices, quantities, expiry dates and trust levels.
- Preserves existing non-demo inventory.
- Replaces inventory previously generated by this script.

Important:
This is simulated demonstration inventory.
It is not verified real-time PM Jan Aushadhi stock.
"""

import asyncio
import re
from datetime import datetime, timedelta, timezone
from typing import Any

from motor.motor_asyncio import AsyncIOMotorClient

from app.core.config import settings


# =====================================================
# MongoDB collection names
# =====================================================

MEDICINES_COLLECTION = "medicines"
KENDRAS_COLLECTION = "kendras"


# =====================================================
# Demo inventory settings
# =====================================================

KENDRAS_PER_MEDICINE = 3

DEMO_BATCH_PREFIX = "DEMO-WSM"

VERIFICATION_LEVELS = [
    "verified",
    "distributor",
    "unverified",
]

PRICE_FACTORS = [
    1.00,
    0.98,
    0.95,
]

EXPIRY_DAYS = [
    240,
    420,
    600,
]


# =====================================================
# Safe medicine-code helper
# =====================================================

def safe_code(value: Any) -> str:
    """
    Convert a PMBI code into a value suitable for use
    inside a demonstration batch number.
    """

    text = str(value or "").strip()

    return re.sub(
        r"[^A-Za-z0-9_-]",
        "-",
        text,
    )


# =====================================================
# Demo quantity generator
# =====================================================

def calculate_quantity(
    medicine_index: int,
    option_index: int,
) -> int:
    """
    Generate a deterministic quantity between 10 and 59.

    Different Kendras receive different quantities so the
    WSM quantity criterion can affect ranking.
    """

    return (
        (
            medicine_index * 17
            + option_index * 13
        ) % 50
    ) + 10


# =====================================================
# Stock-status helper
# =====================================================

def compute_stock_status(
    quantity: int,
) -> str:
    """
    Return the stock-status value expected by the backend.
    """

    if quantity <= 0:
        return "out_of_stock"

    if quantity <= 5:
        return "low_stock"

    return "in_stock"


# =====================================================
# Build one demonstration stock record
# =====================================================

def build_demo_stock_item(
    medicine: dict[str, Any],
    medicine_index: int,
    option_index: int,
    current_time: datetime,
) -> dict[str, Any]:
    """
    Build one inventory item containing one active batch.
    """

    pmbi_code = str(
        medicine.get(
            "pmbi_code",
            "",
        )
    ).strip()

    catalogue_price = float(
        medicine.get(
            "jan_aushadhi_mrp",
            0,
        ) or 0
    )

    quantity = calculate_quantity(
        medicine_index=medicine_index,
        option_index=option_index,
    )

    price_factor = PRICE_FACTORS[
        option_index
        % len(PRICE_FACTORS)
    ]

    selling_price = round(
        max(
            catalogue_price * price_factor,
            0,
        ),
        2,
    )

    expiry_days = EXPIRY_DAYS[
        option_index
        % len(EXPIRY_DAYS)
    ]

    expiry_date = (
        current_time
        + timedelta(
            days=expiry_days,
        )
    )

    verification_status = (
        VERIFICATION_LEVELS[
            option_index
            % len(VERIFICATION_LEVELS)
        ]
    )

    manufacturer = (
        medicine.get("manufacturer")
        or "Bureau of Pharma PSUs of India"
    )

    batch_number = (
        f"{DEMO_BATCH_PREFIX}-"
        f"{safe_code(pmbi_code)}-"
        f"{option_index + 1}"
    )

    return {
        "pmbi_code": pmbi_code,
        "total_qty": quantity,
        "status": compute_stock_status(
            quantity,
        ),
        "batches": [
            {
                "batch_number": batch_number,
                "expiry_date": expiry_date,
                "quantity": quantity,
                "manufacturer": manufacturer,
                "selling_price": selling_price,
                "verification_status":
                    verification_status,
            }
        ],
    }


# =====================================================
# Remove previously generated demo inventory
# =====================================================

def remove_old_demo_items(
    stock: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Remove inventory items generated by an earlier run of
    this script.

    Original inventory that does not use the DEMO-WSM
    batch prefix is preserved.
    """

    preserved_stock: list[
        dict[str, Any]
    ] = []

    for stock_item in stock:
        batches = stock_item.get(
            "batches",
            [],
        )

        contains_demo_batch = any(
            str(
                batch.get(
                    "batch_number",
                    "",
                )
            ).startswith(
                DEMO_BATCH_PREFIX
            )
            for batch in batches
        )

        if not contains_demo_batch:
            preserved_stock.append(
                stock_item
            )

    return preserved_stock


# =====================================================
# Select Kendras for one medicine
# =====================================================

def select_kendra_indices(
    medicine_index: int,
    kendra_count: int,
    required_count: int,
) -> list[int]:
    """
    Select different Kendras for each medicine.

    The selection is deterministic so rerunning the script
    produces stable demonstration data.
    """

    selected_indices: list[int] = []

    preferred_offsets = [
        0,
        7,
        13,
    ]

    for offset in preferred_offsets:
        candidate_index = (
            medicine_index + offset
        ) % kendra_count

        if (
            candidate_index
            not in selected_indices
        ):
            selected_indices.append(
                candidate_index
            )

        if (
            len(selected_indices)
            == required_count
        ):
            return selected_indices

    offset = 0

    while (
        len(selected_indices)
        < required_count
    ):
        candidate_index = (
            medicine_index + offset
        ) % kendra_count

        if (
            candidate_index
            not in selected_indices
        ):
            selected_indices.append(
                candidate_index
            )

        offset += 1

    return selected_indices


# =====================================================
# Main inventory seeding function
# =====================================================

async def seed_demo_inventory() -> None:
    """
    Create demonstration inventory for all medicines.
    """

    client = AsyncIOMotorClient(
        settings.MONGODB_URL
    )

    try:
        database = client[
            settings.DATABASE_NAME
        ]

        await client.admin.command(
            "ping"
        )

        print(
            "Connected to MongoDB:",
            settings.DATABASE_NAME,
        )

        medicines = await database[
            MEDICINES_COLLECTION
        ].find(
            {
                "is_active": {
                    "$ne": False,
                },
                "pmbi_code": {
                    "$exists": True,
                    "$ne": "",
                },
            }
        ).sort(
            "pmbi_code",
            1,
        ).to_list(
            length=None,
        )

        kendras = await database[
            KENDRAS_COLLECTION
        ].find(
            {
                "is_active": {
                    "$ne": False,
                },
            }
        ).sort(
            "name",
            1,
        ).to_list(
            length=None,
        )

        if not medicines:
            raise RuntimeError(
                "No medicines were found. "
                "Run Backend/seed_data.py first."
            )

        if not kendras:
            raise RuntimeError(
                "No Kendras were found. "
                "Run Backend/seed_data.py first."
            )

        print(
            f"Medicines found: "
            f"{len(medicines)}"
        )

        print(
            f"Kendras found: "
            f"{len(kendras)}"
        )

        assignment_count = min(
            KENDRAS_PER_MEDICINE,
            len(kendras),
        )

        current_time = datetime.now(
            timezone.utc
        )

        inventories: dict[
            str,
            list[dict[str, Any]],
        ] = {}

        existing_codes: dict[
            str,
            set[str],
        ] = {}

        # Preserve original inventory and remove only
        # inventory created by a previous script run.
        for kendra in kendras:
            kendra_id = str(
                kendra["_id"]
            )

            preserved_stock = (
                remove_old_demo_items(
                    kendra.get(
                        "stock",
                        [],
                    )
                )
            )

            inventories[kendra_id] = (
                preserved_stock
            )

            existing_codes[kendra_id] = {
                str(
                    stock_item.get(
                        "pmbi_code",
                        "",
                    )
                ).strip()
                for stock_item
                in preserved_stock
                if stock_item.get(
                    "pmbi_code"
                )
            }

        generated_items = 0
        preserved_matches = 0

        # Assign every medicine to multiple Kendras.
        for medicine_index, medicine in enumerate(
            medicines
        ):
            pmbi_code = str(
                medicine.get(
                    "pmbi_code",
                    "",
                )
            ).strip()

            if not pmbi_code:
                continue

            selected_indices = (
                select_kendra_indices(
                    medicine_index=
                        medicine_index,
                    kendra_count=
                        len(kendras),
                    required_count=
                        assignment_count,
                )
            )

            for (
                option_index,
                kendra_index,
            ) in enumerate(
                selected_indices
            ):
                kendra = kendras[
                    kendra_index
                ]

                kendra_id = str(
                    kendra["_id"]
                )

                # Do not duplicate a real inventory item.
                if (
                    pmbi_code
                    in existing_codes[kendra_id]
                ):
                    preserved_matches += 1
                    continue

                demo_stock_item = (
                    build_demo_stock_item(
                        medicine=medicine,
                        medicine_index=
                            medicine_index,
                        option_index=
                            option_index,
                        current_time=
                            current_time,
                    )
                )

                inventories[
                    kendra_id
                ].append(
                    demo_stock_item
                )

                existing_codes[
                    kendra_id
                ].add(
                    pmbi_code
                )

                generated_items += 1

        updated_kendras = 0

        # Save the generated inventory.
        for kendra in kendras:
            kendra_id = str(
                kendra["_id"]
            )

            result = await database[
                KENDRAS_COLLECTION
            ].update_one(
                {
                    "_id": kendra["_id"],
                },
                {
                    "$set": {
                        "stock":
                            inventories[
                                kendra_id
                            ],
                        "updated_at":
                            current_time,
                        "inventory_data_type":
                            "demonstration",
                    }
                },
            )

            if result.modified_count > 0:
                updated_kendras += 1

        print(
            "Demo inventory generation completed."
        )

        print(
            f"Demo stock items generated: "
            f"{generated_items}"
        )

        print(
            f"Existing stock matches preserved: "
            f"{preserved_matches}"
        )

        print(
            f"Kendras updated: "
            f"{updated_kendras}"
        )

        print(
            "Every medicine is now assigned "
            f"to up to {assignment_count} Kendras."
        )

        print(
            "WARNING: This is simulated "
            "demonstration inventory."
        )

    finally:
        client.close()

        print(
            "MongoDB connection closed."
        )


# =====================================================
# Script entry point
# =====================================================

if __name__ == "__main__":
    asyncio.run(
        seed_demo_inventory()
    )