/**
 * Component: RecommendationConfidence
 *
 * Description:
 *   Displays a confidence score card for the generic recommendation,
 *   showing how closely the generic matches the branded medicine.
 *   Values are placeholders — the actual confidence score will be
 *   generated by the backend ML / recommendation engine in future.
 *
 * Responsibilities:
 *   - Confidence score circular placeholder
 *   - Composition match status
 *   - Equivalent status indicator
 *   - Verification placeholder note
 *
 * Backend readiness:
 *   - confidence → GET /api/v1/medicines/:id/recommendation-confidence
 *   This entire section is a UI placeholder until the ML backend is ready.
 */

import { HiOutlineShieldCheck, HiOutlineCheckCircle, HiOutlineInformationCircle } from 'react-icons/hi2'
import Badge from '../../../components/ui/Badge'

// =====================================================
// Confidence Ring SVG placeholder
// =====================================================
function ConfidenceRing({ score = 96 }) {
  const radius = 42
  const circ   = 2 * Math.PI * radius
  const dash   = (score / 100) * circ

  return (
    <div className="flex items-center justify-center" aria-label={`Confidence score: ${score}%`}>
      <svg width="120" height="120" viewBox="0 0 120 120" aria-hidden="true">
        {/* Background ring */}
        <circle cx="60" cy="60" r={radius} fill="none" stroke="#f1f5f9" strokeWidth="10" />
        {/* Score ring */}
        <circle
          cx="60" cy="60" r={radius}
          fill="none"
          stroke="#16a34a"
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={`${dash} ${circ}`}
          strokeDashoffset={circ / 4}
          className="transition-all duration-500"
        />
        {/* Score text */}
        <text x="60" y="55" textAnchor="middle" fontSize="22" fontWeight="800" fill="#15803d" fontFamily="sans-serif">
          {score}%
        </text>
        <text x="60" y="72" textAnchor="middle" fontSize="9" fill="#86efac" fontFamily="sans-serif">
          Confidence
        </text>
      </svg>
    </div>
  )
}

// =====================================================
// Recommendation Confidence
// =====================================================
function RecommendationConfidence({ confidence = {} }) {
  // TODO: replace with GET /api/v1/medicines/:id/recommendation-confidence
  // This value will be generated by the ML recommendation engine in future.
  const {
    score             = 96,
    compositionMatch  = 'Exact Match (100%)',
    equivalentStatus  = 'Therapeutically Equivalent',
    verificationStatus = 'Pending Backend Verification',
  } = confidence

  return (
    <section aria-labelledby="confidence-heading">

      {/* =====================================================
          Recommendation Confidence
         ===================================================== */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
        <div className="flex items-center gap-2 mb-4">
          <HiOutlineShieldCheck size={18} className="text-success-600" aria-hidden="true" />
          <h2 id="confidence-heading" className="text-base font-bold text-slate-900">
            Recommendation Confidence
          </h2>
          <Badge variant="success" size="sm">High Confidence</Badge>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 items-center">
          {/* Confidence ring */}
          <div className="flex flex-col items-center gap-3">
            <ConfidenceRing score={score} />
            <p className="text-xs text-slate-500 text-center max-w-[180px]">
              {/* TODO: score from ML recommendation engine */}
              This confidence score will be generated by the backend recommendation algorithm.
            </p>
          </div>

          {/* Indicators */}
          <div className="flex flex-col gap-3">
            <div className="flex items-start gap-3 p-3 rounded-xl bg-success-50 border border-success-100">
              <HiOutlineCheckCircle size={16} className="text-success-500 mt-0.5 shrink-0" aria-hidden="true" />
              <div>
                <p className="text-xs font-semibold text-success-800">Composition Match</p>
                <p className="text-xs text-success-600 mt-0.5">
                  {/* TODO: compositionMatch from API */}
                  {compositionMatch}
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 p-3 rounded-xl bg-primary-50 border border-primary-100">
              <HiOutlineCheckCircle size={16} className="text-primary-500 mt-0.5 shrink-0" aria-hidden="true" />
              <div>
                <p className="text-xs font-semibold text-primary-800">Equivalent Status</p>
                <p className="text-xs text-primary-600 mt-0.5">
                  {/* TODO: equivalentStatus from API */}
                  {equivalentStatus}
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3 p-3 rounded-xl bg-warning-50 border border-warning-100">
              <HiOutlineInformationCircle size={16} className="text-warning-500 mt-0.5 shrink-0" aria-hidden="true" />
              <div>
                <p className="text-xs font-semibold text-warning-800">Verification Status</p>
                <p className="text-xs text-warning-600 mt-0.5">
                  {/* TODO: verificationStatus from backend verification service */}
                  {verificationStatus}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default RecommendationConfidence
